# Generated by Django 3.2.6 on 2021-09-06 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buttoninfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Button_letter', models.CharField(max_length=80)),
                ('Button_height', models.IntegerField()),
                ('Button_width', models.IntegerField()),
                ('Button_Starting_xpoint', models.IntegerField()),
                ('Button_Starting_ypoint', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='insertbutton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buttonColor', models.CharField(max_length=60)),
            ],
        ),
    ]
